#!/bin/bash
default_commit_mg="UPDATE"
status=`git status --porcelain`
echo -n $status | wc -m
if [[ -z "$status" ]]; then
    echo $status    
    echo "There is not change."
else 
    echo $status
    git add .
    echo "Type commit message if you want"
    read given_commit_mg
    if [[ -n "$given_commit_mg" ]]; then
        git commit -m "$given_commit_mg"
    fi  
        git commit -m "$default_commit_mg"
fi